repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        name: Ruff Auto-Fix (Formatting)
        entry: ruff
        args: ["format"]
        language_version: python3
      - id: ruff
        name: Ruff Lint (Check)
        entry: ruff
        args: ["lint"]
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: Mypy Type Checking
        language_version: python3
